
export const APPLICATION_AUTH_REQUEST = '@@application/APPLICATION_AUTH_REQUEST';
export const APPLICATION_AUTH_REQUEST_FAIL = '@@application/APPLICATION_AUTH_REQUEST_FAIL';
export const APPLICATION_AUTH_REQUEST_SUCCESS = '@@application/APPLICATION_AUTH_REQUEST_SUCCESS';