
export const APPLICATION_AUTH_REQUEST = 'APPLICATION_AUTH_REQUEST';
export const APPLICATION_AUTH_REQUEST_SUCCESS = 'APPLICATION_AUTH_REQUEST_SUCCESS';
export const APPLICATION_AUTH_REQUEST_FAIL = 'APPLICATION_AUTH_REQUEST_FAIL';