
export const DESTROY = '@@stock/DESTROY';

export const GET_CURRENCIES_REQUEST = '@@stock/GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_REQUEST_FAIL = '@@stock/GET_CURRENCIES_REQUEST_FAIL';
export const GET_CURRENCIES_REQUEST_SUCCESS = '@@stock/GET_CURRENCIES_REQUEST_SUCCESS';

export const GET_CATEGORIES_REQUEST = '@@stock/GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_REQUEST_FAIL = '@@stock/GET_CATEGORIES_REQUEST_FAIL';
export const GET_CATEGORIES_REQUEST_SUCCESS = '@@stock/GET_CATEGORIES_REQUEST_SUCCESS';

export const GET_PRODUCTS_REQUEST = '@@stock/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_REQUEST_FAIL = '@@stock/GET_PRODUCTS_REQUEST_FAIL';
export const GET_PRODUCTS_REQUEST_SUCCESS = '@@stock/GET_PRODUCTS_REQUEST_SUCCESS';

export const GET_STOCK_PRODUCTS_REQUEST = '@@stock/GET_STOCK_PRODUCTS_REQUEST';
export const GET_STOCK_PRODUCTS_REQUEST_FAIL = '@@stock/GET_STOCK_PRODUCTS_REQUEST_FAIL';
export const GET_STOCK_PRODUCTS_REQUEST_SUCCESS = '@@stock/GET_STOCK_PRODUCTS_REQUEST_SUCCESS';

export const GET_STOCK_PRODUCTS_BY_ID_REQUEST = '@@stock/GET_STOCK_PRODUCTS_BY_ID_REQUEST';
export const GET_STOCK_PRODUCTS_BY_ID_REQUEST_FAIL = '@@stock/GET_STOCK_PRODUCTS_BY_ID_REQUEST_FAIL';
export const GET_STOCK_PRODUCTS_BY_ID_REQUEST_SUCCESS = '@@stock/GET_STOCK_PRODUCTS_BY_ID_REQUEST_SUCCESS';

export const CREATE_STOCK_PRODUCTS_REQUEST = '@@stock/CREATE_STOCK_PRODUCTS_REQUEST';
export const CREATE_STOCK_PRODUCTS_REQUEST_FAIL = '@@stock/CREATE_STOCK_PRODUCTS_REQUEST_FAIL';
export const CREATE_STOCK_PRODUCTS_REQUEST_SUCCESS = '@@stock/CREATE_STOCK_PRODUCTS_REQUEST_SUCCESS';

export const UPDATE_STOCK_PRODUCTS_REQUEST = '@@stock/UPDATE_STOCK_PRODUCTS_REQUEST';
export const UPDATE_STOCK_PRODUCTS_REQUEST_FAIL = '@@stock/UPDATE_STOCK_PRODUCTS_REQUEST_FAIL';
export const UPDATE_STOCK_PRODUCTS_REQUEST_SUCCESS = '@@stock/UPDATE_STOCK_PRODUCTS_REQUEST_SUCCESS';

export const DELETE_STOCK_PRODUCTS_REQUEST = '@@stock/DELETE_STOCK_PRODUCTS_REQUEST';
export const DELETE_STOCK_PRODUCTS_REQUEST_FAIL = '@@stock/DELETE_STOCK_PRODUCTS_REQUEST_FAIL';
export const DELETE_STOCK_PRODUCTS_REQUEST_SUCCESS = '@@stock/DELETE_STOCK_PRODUCTS_REQUEST_SUCCESS';


export const SOCKET_STOCK_PRODUCT_CREATED = '@@socket/STOCK_PRODUCT_CREATED';
export const SOCKET_STOCK_PRODUCT_UPDATED = '@@socket/STOCK_PRODUCT_UPDATED';
export const SOCKET_STOCK_PRODUCT_DELETED = '@@socket/STOCK_PRODUCT_DELETED';