
export const SIGN_OUT = '@application/SIGN_OUT';

export const RESET = '@product/RESET';

export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_UNITS_REQUEST = '@product/GET_UNITS_REQUEST';
export const GET_UNITS_REQUEST_FAIL = '@product/GET_UNITS_REQUEST_FAIL';
export const GET_UNITS_REQUEST_SUCCESS = '@product/GET_UNITS_REQUEST_SUCCESS';

export const GET_PRODUCT_REQUEST = '@product/GET_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST_FAIL = '@product/GET_PRODUCT_REQUEST_FAIL';
export const GET_PRODUCT_REQUEST_SUCCESS = '@product/GET_PRODUCT_REQUEST_SUCCESS';

export const UPDATE_PRODUCT_REQUEST = '@product/UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST_FAIL = '@product/UPDATE_PRODUCT_REQUEST_FAIL';
export const UPDATE_PRODUCT_REQUEST_SUCCESS = '@product/UPDATE_PRODUCT_REQUEST_SUCCESS';

export const CREATE_PRODUCT_REQUEST = '@product/CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_REQUEST_FAIL = '@product/CREATE_PRODUCT_REQUEST_FAIL';
export const CREATE_PRODUCT_REQUEST_SUCCESS = '@product/CREATE_PRODUCT_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
