
export const SIGN_OUT = '@application/SIGN_OUT';

export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_CURRENCIES_REQUEST = '@currencies/GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_REQUEST_FAIL = '@currencies/GET_CURRENCIES_REQUEST_FAIL';
export const GET_CURRENCIES_REQUEST_SUCCESS = '@currencies/GET_CURRENCIES_REQUEST_SUCCESS';

export const ADD_CURRENCY_REQUEST = '@currencies/ADD_CURRENCY_REQUEST';
export const ADD_CURRENCY_REQUEST_FAIL = '@currencies/ADD_CURRENCY_REQUEST_FAIL';
export const ADD_CURRENCY_REQUEST_SUCCESS = '@currencies/ADD_CURRENCY_REQUEST_SUCCESS';

export const GET_CURRENCY_REQUEST = '@currencies/GET_CURRENCY_REQUEST';
export const GET_CURRENCY_REQUEST_FAIL = '@currencies/GET_CURRENCY_REQUEST_FAIL';
export const GET_CURRENCY_REQUEST_SUCCESS = '@currencies/GET_CURRENCY_REQUEST_SUCCESS';

export const UPDATE_CURRENCY_REQUEST = '@currencies/UPDATE_CURRENCY_REQUEST';
export const UPDATE_CURRENCY_REQUEST_FAIL = '@currencies/UPDATE_CURRENCY_REQUEST_FAIL';
export const UPDATE_CURRENCY_REQUEST_SUCCESS = '@currencies/UPDATE_CURRENCY_REQUEST_SUCCESS';

export const DELETE_CURRENCY_REQUEST = '@currencies/DELETE_CURRENCY_REQUEST';
export const DELETE_CURRENCY_REQUEST_FAIL = '@currencies/DELETE_CURRENCY_REQUEST_FAIL';
export const DELETE_CURRENCY_REQUEST_SUCCESS = '@currencies/DELETE_CURRENCY_REQUEST_SUCCESS';
