
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const CREATE_OPERATION_REQUEST = '@cart/CREATE_OPERATION_REQUEST';
export const CREATE_OPERATION_REQUEST_FAIL = '@cart/CREATE_OPERATION_REQUEST_FAIL';
export const CREATE_OPERATION_REQUEST_SUCCESS = '@cart/CREATE_OPERATION_REQUEST_SUCCESS';

export const GET_LENSES_REQUEST = '@order/GET_LENSES_REQUEST';
export const GET_LENSES_REQUEST_FAIL = '@order/GET_LENSES_REQUEST_FAIL';
export const GET_LENSES_REQUEST_SUCCESS = '@order/GET_LENSES_REQUEST_SUCCESS';
