
version: "3.7"
services:

  db:
    container_name: postgre_sql
    build: ./postgresql
    ports:
      - "54320:5432"

#  rabbit:
#    container_name: rabbit_mq
#    build: ./rabbit
#    ports:
#      - "15672"
#      - "5672"

  identity_srv:
    container_name: identity_srv
    build:
      context: ./
      dockerfile: Dockerfile.identity-srv
    links:
      - "db"
    ports:
      - "8080"
    volumes:
      - "./src/identity_srv/.env.production:/app/src/identity_srv/.env.production"

#  product_proxy:
#    container_name: product_proxy
#    build:
#      context: ./
#      dockerfile: Dockerfile.product-proxy
#    links:
#      - "db"
#      - "rabbit"
#    ports:
#      - "8080"
#    volumes:
#      - "./src/product-proxy/.env.production:/app/src/product-proxy/.env.production"
#
#  admin_gw:
#    container_name: admin_gw
#    build:
#      context: ./
#      dockerfile: Dockerfile.admin-gw
#    links:
#      - "rabbit"
#      - "product_proxy"
#      - "identity_srv"
#    ports:
#      - "8080"
#    volumes:
#      - "./src/admin-gw/.env.production:/app/src/admin-gw/.env.production"
#
#  showcase_gw:
#    container_name: showcase_gw
#    build:
#      context: ./
#      dockerfile: Dockerfile.showcase-gw
#    links:
#      - "rabbit"
#      - "product_proxy"
#    ports:
#      - "8080"
#    volumes:
#      - "./src/showcase-gw/.env.production:/app/src/showcase-gw/.env.production"
#
#  admin_ui:
#    container_name: admin_ui
#    build:
#      context: ./
#      dockerfile: Dockerfile.admin-ui
#    links:
#      - "admin_gw:admin_gw"
#    ports:
#      - "8080:8080"
#    volumes:
#      - "./src/admin-ui/.env.production:/app/src/admin-ui/.env.production"
#      - "./src/admin-ui/nginx/mime.types:/etc/nginx/mime.types"
#      - "./src/admin-ui/nginx/nginx.conf:/etc/nginx/nginx.conf"
#
#  showcase_ui:
#    container_name: showcase_ui
#    build:
#      context: ./
#      dockerfile: Dockerfile.showcase-ui
#    links:
#      - "showcase_gw"
#    ports:
#      - "80:8080"
#    volumes:
#      - "./src/showcase-ui/.env.production:/app/src/showcase-ui/.env.production"
#      - "./src/showcase-ui/nginx/mime.types:/etc/nginx/mime.types"
#      - "./src/showcase-ui/nginx/nginx.conf:/etc/nginx/nginx.conf"