#nginx:
#  build: ./nginx
#  container_name: nginx
#  links:
#    - web:web
#    - api:api
#  ports:
#    - "80:80"
#
#web:
#  build: ./web
#  container_name: web
#  ports:
#    - "8080"
#
#api:
#  build: ./api
#  container_name: api
#  ports:
#    - "8080"

version: "3.7"
services:

  rabbitmq:
    container_name: rabbitmq
    build: ./rabbit
    ports:
      - "8080:15672"
      - "5672"

  admin-gw:
    container_name: admin-gw
    build:
      context: ./
      dockerfile: Dockerfile.admin-gw
    links:
      - "rabbitmq:rabbitmq"
    ports:
      - "8080"

  showcase-gw:
    container_name: showcase-gw
    build:
      context: ./
      dockerfile: Dockerfile.showcase-gw
    links:
      - "rabbitmq:rabbitmq"
    ports:
      - "8080"