
# BUILD APP
FROM node:11-alpine as ui

WORKDIR /

RUN npm config set package-lock false
RUN npm i yarn -g --yes

WORKDIR /app

RUN yarn

WORKDIR /app/src/admin-ui

RUN ls

RUN tail ./.env.production

RUN ["yarn", "run", "ui:build"]
RUN ["yarn", "run", "dialog:build"]
RUN ["yarn", "run", "notification:build"]

RUN ["yarn", "run", "build"]


# START NGINX
FROM nginx

EXPOSE 80

COPY --from=ui /app/src/admin-ui/build /app

WORKDIR /etc/nginx

CMD ["nginx", "-g", "daemon off;"]
