
# BUILD APP
FROM node:11-alpine

EXPOSE 8080

RUN npm config set package-lock false
RUN npm i yarn -g --yes

WORKDIR /app

RUN yarn

WORKDIR /app/src/identity-srv

ENTRYPOINT ["yarn", "run", "start"]
