
# BUILD APP
FROM node:11-alpine

RUN npm config set package-lock false
RUN npm i yarn -g --yes

WORKDIR /app

COPY ./src/admin-gw/src               ./src/admin-gw/src
COPY ./src/admin-gw/.env.production   ./src/admin-gw
COPY ./src/admin-gw/package.json      ./src/admin-gw
COPY ./packages                       ./packages
COPY ./package.json                   .
COPY ./lerna.json                     .

RUN yarn

WORKDIR /app/src/admin-gw

ENTRYPOINT ["yarn", "run", "start"]
