
# BUILD APP
FROM node:11-alpine as ui

RUN npm config set package-lock false
RUN npm i yarn -g --yes

WORKDIR /app

RUN yarn

WORKDIR /app/src/showcase-ui

RUN ["yarn", "run", "ui:build"]
RUN ["yarn", "run", "tabs:build"]
RUN ["yarn", "run", "dialog:build"]
RUN ["yarn", "run", "notification:build"]

RUN ["yarn", "run", "build"]


# START NGINX
FROM nginx

COPY --from=ui /app/src/showcase-ui/build /app

WORKDIR /etc/nginx

CMD ["nginx", "-g", "daemon off;"]
