
version: "3.7"
services:

  db:
    container_name: postgre_sql
    build: ./postgresql
    restart: always
    ports:
      - 50004:5432

  rabbit:
    container_name: rabbit_mq
    build: ./rabbit
    restart: always
    ports:
      - 50002:15672

  identity_srv:
    container_name: identity_srv
    build:
      context: ./
      dockerfile: Dockerfile.identity-srv
    restart: always
    depends_on:
      - db
    links:
      - db


  product_proxy:
    container_name: product_proxy
    build:
      context: ./
      dockerfile: Dockerfile.product-proxy
    restart: always
    depends_on:
      - db
      - rabbit
    links:
      - db
      - rabbit


  admin_gw:
    container_name: admin_gw
    build:
      context: ./
      dockerfile: Dockerfile.admin-gw
    restart: always
    depends_on:
      - rabbit
      - product_proxy
      - identity_srv
    links:
      - rabbit
      - product_proxy
      - identity_srv


  showcase_gw:
    container_name: showcase_gw
    build:
      context: ./
      dockerfile: Dockerfile.showcase-gw
    restart: always
    depends_on:
      - rabbit
      - product_proxy
    links:
      - rabbit
      - product_proxy


  admin_ui:
    container_name: admin_ui
    build:
      context: ./
      dockerfile: Dockerfile.admin-ui
    restart: always
    depends_on:
      - admin_gw
    links:
      - admin_gw
    volumes:
      - ./apps/admin-ui/nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - NODE_ENV=production


  showcase_ui:
    container_name: showcase_ui
    build:
      context: ./
      dockerfile: Dockerfile.showcase-ui
    restart: always
    depends_on:
      - showcase_gw
    links:
      - showcase_gw
    volumes:
      - ./apps/showcase-ui/nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - NODE_ENV=production

  certbot:
    user: root
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

#  prerender:
#    container_name: prerender_srv
#    build:
#      context: ./
#      dockerfile: Dockerfile.prerender-srv
#    restart: always
#    depends_on:
#      - showcase_ui
#      - showcase_gw
#      - product_proxy
#    ports:
#    - 8080:8080

  proxy:
    user: root
    container_name: proxy
    build: ./nginx
    restart: unless-stopped
    depends_on:
      - admin_ui
      - showcase_ui
    links:
      - admin_ui
      - showcase_ui
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/init-letsencrypt.sh:/etc/nginx/init-letsencrypt.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
