
export const SIGN_OUT = '@application/SIGN_OUT';

export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';


export const GET_TYPES_REQUEST = '@attributes/GET_TYPES_REQUEST';
export const GET_TYPES_REQUEST_FAIL = '@attributes/GET_TYPES_REQUEST_FAIL';
export const GET_TYPES_REQUEST_SUCCESS = '@attributes/GET_TYPES_REQUEST_SUCCESS';

export const CREATE_TYPE_REQUEST = '@attributes/CREATE_TYPE_REQUEST';
export const CREATE_TYPE_REQUEST_FAIL = '@attributes/CREATE_TYPE_REQUEST_FAIL';
export const CREATE_TYPE_REQUEST_SUCCESS = '@attributes/CREATE_TYPE_REQUEST_SUCCESS';

export const UPDATE_TYPE_REQUEST = '@attributes/UPDATE_TYPE_REQUEST';
export const UPDATE_TYPE_REQUEST_FAIL = '@attributes/UPDATE_TYPE_REQUEST_FAIL';
export const UPDATE_TYPE_REQUEST_SUCCESS = '@attributes/UPDATE_TYPE_REQUEST_SUCCESS';

export const DELETE_TYPES_REQUEST = '@attributes/DELETE_TYPES_REQUEST';
export const DELETE_TYPES_REQUEST_FAIL = '@attributes/DELETE_TYPES_REQUEST_FAIL';
export const DELETE_TYPES_REQUEST_SUCCESS = '@attributes/DELETE_TYPES_REQUEST_SUCCESS';


export const GET_CATEGORIES_REQUEST = '@attributes/GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_REQUEST_FAIL = '@attributes/GET_CATEGORIES_REQUEST_FAIL';
export const GET_CATEGORIES_REQUEST_SUCCESS = '@attributes/GET_CATEGORIES_REQUEST_SUCCESS';

export const CREATE_CATEGORY_REQUEST = '@attributes/CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_REQUEST_FAIL = '@attributes/CREATE_CATEGORY_REQUEST_FAIL';
export const CREATE_CATEGORY_REQUEST_SUCCESS = '@attributes/CREATE_CATEGORY_REQUEST_SUCCESS';

export const UPDATE_CATEGORY_REQUEST = '@attributes/UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_REQUEST_FAIL = '@attributes/UPDATE_CATEGORY_REQUEST_FAIL';
export const UPDATE_CATEGORY_REQUEST_SUCCESS = '@attributes/UPDATE_CATEGORY_REQUEST_SUCCESS';

export const DELETE_CATEGORIES_REQUEST = '@attributes/DELETE_CATEGORIES_REQUEST';
export const DELETE_CATEGORIES_REQUEST_FAIL = '@attributes/DELETE_CATEGORIES_REQUEST_FAIL';
export const DELETE_CATEGORIES_REQUEST_SUCCESS = '@attributes/DELETE_CATEGORIES_REQUEST_SUCCESS';


export const GET_COLORS_REQUEST = '@attributes/GET_COLORS_REQUEST';
export const GET_COLORS_REQUEST_FAIL = '@attributes/GET_COLORS_REQUEST_FAIL';
export const GET_COLORS_REQUEST_SUCCESS = '@attributes/GET_COLORS_REQUEST_SUCCESS';

export const CREATE_COLOR_REQUEST = '@attributes/CREATE_COLOR_REQUEST';
export const CREATE_COLOR_REQUEST_FAIL = '@attributes/CREATE_COLOR_REQUEST_FAIL';
export const CREATE_COLOR_REQUEST_SUCCESS = '@attributes/CREATE_COLOR_REQUEST_SUCCESS';

export const UPDATE_COLOR_REQUEST = '@attributes/UPDATE_COLOR_REQUEST';
export const UPDATE_COLOR_REQUEST_FAIL = '@attributes/UPDATE_COLOR_REQUEST_FAIL';
export const UPDATE_COLOR_REQUEST_SUCCESS = '@attributes/UPDATE_COLOR_REQUEST_SUCCESS';

export const DELETE_COLORS_REQUEST = '@attributes/DELETE_COLORS_REQUEST';
export const DELETE_COLORS_REQUEST_FAIL = '@attributes/DELETE_COLORS_REQUEST_FAIL';
export const DELETE_COLORS_REQUEST_SUCCESS = '@attributes/DELETE_COLORS_REQUEST_SUCCESS';


export const GET_MATERIALS_REQUEST = '@attributes/GET_MATERIALS_REQUEST';
export const GET_MATERIALS_REQUEST_FAIL = '@attributes/GET_MATERIALS_REQUEST_FAIL';
export const GET_MATERIALS_REQUEST_SUCCESS = '@attributes/GET_MATERIALS_REQUEST_SUCCESS';

export const CREATE_MATERIAL_REQUEST = '@attributes/CREATE_MATERIAL_REQUEST';
export const CREATE_MATERIAL_REQUEST_FAIL = '@attributes/CREATE_MATERIAL_REQUEST_FAIL';
export const CREATE_MATERIAL_REQUEST_SUCCESS = '@attributes/CREATE_MATERIAL_REQUEST_SUCCESS';

export const UPDATE_MATERIAL_REQUEST = '@attributes/UPDATE_MATERIAL_REQUEST';
export const UPDATE_MATERIAL_REQUEST_FAIL = '@attributes/UPDATE_MATERIAL_REQUEST_FAIL';
export const UPDATE_MATERIAL_REQUEST_SUCCESS = '@attributes/UPDATE_MATERIAL_REQUEST_SUCCESS';

export const DELETE_MATERIALS_REQUEST = '@attributes/DELETE_MATERIALS_REQUEST';
export const DELETE_MATERIALS_REQUEST_FAIL = '@attributes/DELETE_MATERIALS_REQUEST_FAIL';
export const DELETE_MATERIALS_REQUEST_SUCCESS = '@attributes/DELETE_MATERIALS_REQUEST_SUCCESS';


export const GET_FORMS_REQUEST = '@attributes/GET_FORMS_REQUEST';
export const GET_FORMS_REQUEST_FAIL = '@attributes/GET_FORMS_REQUEST_FAIL';
export const GET_FORMS_REQUEST_SUCCESS = '@attributes/GET_FORMS_REQUEST_SUCCESS';

export const CREATE_FORM_REQUEST = '@attributes/CREATE_FORM_REQUEST';
export const CREATE_FORM_REQUEST_FAIL = '@attributes/CREATE_FORM_REQUEST_FAIL';
export const CREATE_FORM_REQUEST_SUCCESS = '@attributes/CREATE_FORM_REQUEST_SUCCESS';

export const UPDATE_FORM_REQUEST = '@attributes/UPDATE_FORM_REQUEST';
export const UPDATE_FORM_REQUEST_FAIL = '@attributes/UPDATE_FORM_REQUEST_FAIL';
export const UPDATE_FORM_REQUEST_SUCCESS = '@attributes/UPDATE_FORM_REQUEST_SUCCESS';

export const DELETE_FORMS_REQUEST = '@attributes/DELETE_FORMS_REQUEST';
export const DELETE_FORMS_REQUEST_FAIL = '@attributes/DELETE_FORMS_REQUEST_FAIL';
export const DELETE_FORMS_REQUEST_SUCCESS = '@attributes/DELETE_FORMS_REQUEST_SUCCESS';


export const GET_CURRENCIES_REQUEST = '@attributes/GET_CURRENCIES_REQUEST';
export const GET_CURRENCIES_REQUEST_FAIL = '@attributes/GET_CURRENCIES_REQUEST_FAIL';
export const GET_CURRENCIES_REQUEST_SUCCESS = '@attributes/GET_CURRENCIES_REQUEST_SUCCESS';

export const CREATE_CURRENCY_REQUEST = '@attributes/CREATE_CURRENCY_REQUEST';
export const CREATE_CURRENCY_REQUEST_FAIL = '@attributes/CREATE_CURRENCY_REQUEST_FAIL';
export const CREATE_CURRENCY_REQUEST_SUCCESS = '@attributes/CREATE_CURRENCY_REQUEST_SUCCESS';

export const UPDATE_CURRENCY_REQUEST = '@attributes/UPDATE_CURRENCY_REQUEST';
export const UPDATE_CURRENCY_REQUEST_FAIL = '@attributes/UPDATE_CURRENCY_REQUEST_FAIL';
export const UPDATE_CURRENCY_REQUEST_SUCCESS = '@attributes/UPDATE_CURRENCY_REQUEST_SUCCESS';

export const DELETE_CURRENCIES_REQUEST = '@attributes/DELETE_CURRENCIES_REQUEST';
export const DELETE_CURRENCIES_REQUEST_FAIL = '@attributes/DELETE_CURRENCIES_REQUEST_FAIL';
export const DELETE_CURRENCIES_REQUEST_SUCCESS = '@attributes/DELETE_CURRENCIES_REQUEST_SUCCESS';


export const GET_UNITS_REQUEST = '@attributes/GET_UNITS_REQUEST';
export const GET_UNITS_REQUEST_FAIL = '@attributes/GET_UNITS_REQUEST_FAIL';
export const GET_UNITS_REQUEST_SUCCESS = '@attributes/GET_UNITS_REQUEST_SUCCESS';

export const CREATE_UNIT_REQUEST = '@attributes/CREATE_UNIT_REQUEST';
export const CREATE_UNIT_REQUEST_FAIL = '@attributes/CREATE_UNIT_REQUEST_FAIL';
export const CREATE_UNIT_REQUEST_SUCCESS = '@attributes/CREATE_UNIT_REQUEST_SUCCESS';

export const UPDATE_UNIT_REQUEST = '@attributes/UPDATE_UNIT_REQUEST';
export const UPDATE_UNIT_REQUEST_FAIL = '@attributes/UPDATE_UNIT_REQUEST_FAIL';
export const UPDATE_UNIT_REQUEST_SUCCESS = '@attributes/UPDATE_UNIT_REQUEST_SUCCESS';

export const DELETE_UNITS_REQUEST = '@attributes/DELETE_UNITS_REQUEST';
export const DELETE_UNITS_REQUEST_FAIL = '@attributes/DELETE_UNITS_REQUEST_FAIL';
export const DELETE_UNITS_REQUEST_SUCCESS = '@attributes/DELETE_UNITS_REQUEST_SUCCESS';
