
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST_FAIL = 'GET_PRODUCT_REQUEST_FAIL';
export const GET_PRODUCT_REQUEST_SUCCESS = 'GET_PRODUCT_REQUEST_SUCCESS';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST_FAIL = 'UPDATE_PRODUCT_REQUEST_FAIL';
export const UPDATE_PRODUCT_REQUEST_SUCCESS = 'UPDATE_PRODUCT_REQUEST_SUCCESS';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_REQUEST_FAIL = 'CREATE_PRODUCT_REQUEST_FAIL';
export const CREATE_PRODUCT_REQUEST_SUCCESS = 'CREATE_PRODUCT_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
