
export const SIGN_OUT = '@application/SIGN_OUT';

export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_OPERATIONS_REQUEST = '@orders/GET_OPERATIONS_REQUEST';
export const GET_OPERATIONS_REQUEST_FAIL = '@orders/GET_OPERATIONS_REQUEST_FAIL';
export const GET_OPERATIONS_REQUEST_SUCCESS = '@orders/GET_OPERATIONS_REQUEST_SUCCESS';