
export const GET_UNITS_REQUEST = '@units/GET_UNITS_REQUEST';
export const GET_UNITS_REQUEST_FAIL = '@units/GET_UNITS_REQUEST_FAIL';
export const GET_UNITS_REQUEST_SUCCESS = '@units/GET_UNITS_REQUEST_SUCCESS';

export const CREATE_UNIT_REQUEST = '@units/CREATE_UNIT_REQUEST';
export const CREATE_UNIT_REQUEST_FAIL = '@units/CREATE_UNIT_REQUEST_FAIL';
export const CREATE_UNIT_REQUEST_SUCCESS = '@units/CREATE_UNIT_REQUEST_SUCCESS';

export const UPDATE_UNIT_REQUEST = '@units/UPDATE_UNIT_REQUEST';
export const UPDATE_UNIT_REQUEST_FAIL = '@units/UPDATE_UNIT_REQUEST_FAIL';
export const UPDATE_UNIT_REQUEST_SUCCESS = '@units/UPDATE_UNIT_REQUEST_SUCCESS';

export const REMOVE_UNIT_REQUEST = '@units/REMOVE_UNIT_REQUEST';
export const REMOVE_UNIT_REQUEST_FAIL = '@units/REMOVE_UNIT_REQUEST_FAIL';
export const REMOVE_UNIT_REQUEST_SUCCESS = '@units/REMOVE_UNIT_REQUEST_SUCCESS';

export const SOCKET_UNIT_CREATED = '@@socket/UNIT_CREATED';
export const SOCKET_UNIT_UPDATED = '@@socket/UNIT_UPDATED';
export const SOCKET_UNIT_DELETED = '@@socket/UNIT_DELETED';