
export const OPEN_DIALOG = '@sub-products/OPEN_DIALOG';
export const CLOSE_DIALOG = '@sub-products/CLOSE_DIALOG';

export const GET_SUB_PRODUCTS_REQUEST = '@sub-products/GET_PRODUCTS_REQUEST';
export const GET_SUB_PRODUCTS_REQUEST_FAIL = '@sub-products/GET_PRODUCTS_REQUEST_FAIL';
export const GET_SUB_PRODUCTS_REQUEST_SUCCESS = '@sub-products/GET_PRODUCTS_REQUEST_SUCCESS';

export const CREATE_SUB_PRODUCTS_REQUEST = '@sub-products/CREATE_PRODUCTS_REQUEST';
export const CREATE_SUB_PRODUCTS_REQUEST_FAIL = '@sub-products/CREATE_PRODUCTS_REQUEST_FAIL';
export const CREATE_SUB_PRODUCTS_REQUEST_SUCCESS = '@sub-products/CREATE_PRODUCTS_REQUEST_SUCCESS';

export const REMOVE_SUB_PRODUCT_REQUEST = '@sub-products/REMOVE_PRODUCT_REQUEST';
export const REMOVE_SUB_PRODUCT_REQUEST_FAIL = '@sub-products/REMOVE_PRODUCT_REQUEST_FAIL';
export const REMOVE_SUB_PRODUCT_REQUEST_SUCCESS = '@sub-products/REMOVE_PRODUCT_REQUEST_SUCCESS';

export const SOCKET_SUB_PRODUCT_UPDATED = '@@socket/SUB_PRODUCT_UPDATED';
export const SOCKET_SUB_PRODUCT_CREATED = '@@socket/SUB_PRODUCT_CREATED';
export const SOCKET_SUB_PRODUCT_DELETED = '@@socket/SUB_PRODUCT_DELETED';
