
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const ADD_PRODUCT_TO_CART = '@cart/ADD_PRODUCT_TO_CART';

export const NEXT_PAGE = '@showcase/NEXT_PAGE';

export const GET_PRODUCTS_REQUEST = '@showcase/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_REQUEST_FAIL = '@showcase/GET_PRODUCTS_REQUEST_FAIL';
export const GET_PRODUCTS_REQUEST_SUCCESS = '@showcase/GET_PRODUCTS_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = process.env['REACT_APP_SOCKET_PRODUCT_UPDATED'];
