
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const ADD_PRODUCT_TO_CART = '@cart/ADD_PRODUCT_TO_CART';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const GET_PRODUCTS_REQUEST = '@showcase-ui-gw/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_REQUEST_FAIL = '@showcase-ui-gw/GET_PRODUCTS_REQUEST_FAIL';
export const GET_PRODUCTS_REQUEST_SUCCESS = '@showcase-ui-gw/GET_PRODUCTS_REQUEST_SUCCESS';

export const GET_ADDITIONAL_DATA_REQUEST = '@showcase-ui-gw/GET_ADDITIONAL_DATA_REQUEST';
export const GET_ADDITIONAL_DATA_REQUEST_FAIL = '@showcase-ui-gw/GET_ADDITIONAL_DATA_REQUEST_FAIL';
export const GET_ADDITIONAL_DATA_REQUEST_SUCCESS = '@showcase-ui-gw/GET_ADDITIONAL_DATA_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
export const SOCKET_STOCK_PRODUCT_UPDATED = '@@socket/STOCK_PRODUCT_UPDATED';
