
export const CREATE_OPERATION_REQUEST = '@cart/CREATE_OPERATION_REQUEST';
export const CREATE_OPERATION_REQUEST_FAIL = '@cart/CREATE_OPERATION_REQUEST_FAIL';
export const CREATE_OPERATION_REQUEST_SUCCESS = '@cart/CREATE_OPERATION_REQUEST_SUCCESS';