
export const GET_CATEGORIES_REQUEST = '@@category/GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_REQUEST_FAIL = '@@category/GET_CATEGORIES_REQUEST_FAIL';
export const GET_CATEGORIES_REQUEST_SUCCESS = '@@category/GET_CATEGORIES_REQUEST_SUCCESS';

export const CREATE_CATEGORY_REQUEST = '@@category/CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_REQUEST_FAIL = '@@category/CREATE_CATEGORY_REQUEST_FAIL';
export const CREATE_CATEGORY_REQUEST_SUCCESS = '@@category/CREATE_CATEGORY_REQUEST_SUCCESS';

export const UPDATE_CATEGORY_REQUEST = '@@category/UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_REQUEST_FAIL = '@@category/UPDATE_CATEGORY_REQUEST_FAIL';
export const UPDATE_CATEGORY_REQUEST_SUCCESS = '@@category/UPDATE_CATEGORY_REQUEST_SUCCESS';

export const DELETE_CATEGORY_REQUEST = '@@category/DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_REQUEST_FAIL = '@@category/DELETE_CATEGORY_REQUEST_FAIL';
export const DELETE_CATEGORY_REQUEST_SUCCESS = '@@category/DELETE_CATEGORY_REQUEST_SUCCESS';
