
export const OPEN_CART_LIST = 'OPEN_CART_LIST';
export const CLOSE_CART_LIST = 'CLOSE_CART_LIST';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
