
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_REQUEST_FAIL = 'GET_PRODUCTS_REQUEST_FAIL';
export const GET_PRODUCTS_REQUEST_SUCCESS = 'GET_PRODUCTS_REQUEST_SUCCESS';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_REQUEST_FAIL = 'REMOVE_PRODUCT_REQUEST_FAIL';
export const REMOVE_PRODUCT_REQUEST_SUCCESS = 'REMOVE_PRODUCT_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
export const SOCKET_PRODUCT_DELETED = '@@socket/PRODUCT_DELETED';