
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const ADD_PRODUCT_TO_CART = '@cart/ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = '@cart/REMOVE_PRODUCT_FROM_CART';

export const GET_PRODUCT_BY_ID_REQUEST = '@product/GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_REQUEST_FAIL = '@product/GET_PRODUCT_BY_ID_REQUEST_FAIL';
export const GET_PRODUCT_BY_ID_REQUEST_SUCCESS = '@product/GET_PRODUCT_BY_ID_REQUEST_SUCCESS';

export const CREATE_COMMENT_REQUEST = '@product/CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_REQUEST_FAIL = '@product/CREATE_COMMENT_REQUEST_FAIL';
export const CREATE_COMMENT_REQUEST_SUCCESS = '@product/CREATE_COMMENT_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = process.env['REACT_APP_SOCKET_PRODUCT_UPDATED'];
