
export const SIGN_OUT = '@application/SIGN_OUT';

export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_COMMENTS_REQUEST = '@comments/GET_COMMENTS_REQUEST';
export const GET_COMMENTS_REQUEST_FAIL = '@comments/GET_COMMENTS_REQUEST_FAIL';
export const GET_COMMENTS_REQUEST_SUCCESS = '@comments/GET_COMMENTS_REQUEST_SUCCESS';

export const GET_COMMENT_REQUEST = '@comments/GET_COMMENT_REQUEST';
export const GET_COMMENT_REQUEST_FAIL = '@comments/GET_COMMENT_REQUEST_FAIL';
export const GET_COMMENT_REQUEST_SUCCESS = '@comments/GET_COMMENT_REQUEST_SUCCESS';

export const UPDATE_COMMENT_REQUEST = '@comments/UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_REQUEST_FAIL = '@comments/UPDATE_COMMENT_REQUEST_FAIL';
export const UPDATE_COMMENT_REQUEST_SUCCESS = '@comments/UPDATE_COMMENT_REQUEST_SUCCESS';

export const DELETE_COMMENT_REQUEST = '@comments/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_REQUEST_FAIL = '@comments/DELETE_COMMENT_REQUEST_FAIL';
export const DELETE_COMMENT_REQUEST_SUCCESS = '@comments/DELETE_COMMENT_REQUEST_SUCCESS';

export const SOCKET_COMMENT_UPDATED = '@@socket/COMMENT_UPDATED';
export const SOCKET_COMMENT_CREATED = '@@socket/COMMENT_CREATED';
export const SOCKET_COMMENTS_DELETED = '@@socket/COMMENTS_DELETED';
