
export const APPLICATION_CHANGE_STATE = '@application/APPLICATION_CHANGE_STATE';

export const APPLICATION_GET_PROFILE_REQUEST = '@application/APPLICATION_GET_PROFILE_REQUEST';
export const APPLICATION_GET_PROFILE_REQUEST_FAIL = '@application/APPLICATION_GET_PROFILE_REQUEST_FAIL';
export const APPLICATION_GET_PROFILE_REQUEST_SUCCESS = '@application/APPLICATION_GET_PROFILE_REQUEST_SUCCESS';

export const SOCKET_PASSPORT_UPDATED = '@@socket/PASSPORT_UPDATED';