
export const SIGN_OUT = '@application/SIGN_OUT';
export const APPLICATION_CHANGE_STATE = '@application/APPLICATION_CHANGE_STATE';

export const APPLICATION_AUTH_REQUEST = '@@application/APPLICATION_AUTH_REQUEST';
export const APPLICATION_AUTH_REQUEST_FAIL = '@@application/APPLICATION_AUTH_REQUEST_FAIL';
export const APPLICATION_AUTH_REQUEST_SUCCESS = '@@application/APPLICATION_AUTH_REQUEST_SUCCESS';

export const APPLICATION_GET_PROFILE_REQUEST = '@application/APPLICATION_GET_PROFILE_REQUEST';
export const APPLICATION_GET_PROFILE_REQUEST_FAIL = '@application/APPLICATION_GET_PROFILE_REQUEST_FAIL';
export const APPLICATION_GET_PROFILE_REQUEST_SUCCESS = '@application/APPLICATION_GET_PROFILE_REQUEST_SUCCESS';

export const APPLICATION_SIG_OUT_REQUEST = '@application/APPLICATION_SIG_OUT_REQUEST';
export const APPLICATION_SIG_OUT_REQUEST_FAIL = '@application/APPLICATION_SIG_OUT_REQUEST_FAIL';
export const APPLICATION_SIG_OUT_REQUEST_SUCCESS = '@application/APPLICATION_SIG_OUT_REQUEST_SUCCESS';

export const SOCKET_PASSPORT_UPDATED = '@@socket/PASSPORT_UPDATED';