
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_OPERATION_BY_ID_REQUEST = '@operation/GET_OPERATION_BY_ID_REQUEST';
export const GET_OPERATION_BY_ID_REQUEST_FAIL = '@operation/GET_OPERATION_BY_ID_REQUEST_FAIL';
export const GET_OPERATION_BY_ID_REQUEST_SUCCESS = '@operation/GET_OPERATION_BY_ID_REQUEST_SUCCESS';
