
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const GET_PRODUCT_BY_ID_REQUEST = '@product/GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_REQUEST_FAIL = '@product/GET_PRODUCT_BY_ID_REQUEST_FAIL';
export const GET_PRODUCT_BY_ID_REQUEST_SUCCESS = '@product/GET_PRODUCT_BY_ID_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
