
export const ADD_PRODUCT_TO_CART = '@cart/ADD_PRODUCT_TO_CART';

export const GET_PRODUCT_BY_ID_REQUEST = '@product/GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_REQUEST_FAIL = '@product/GET_PRODUCT_BY_ID_REQUEST_FAIL';
export const GET_PRODUCT_BY_ID_REQUEST_SUCCESS = '@product/GET_PRODUCT_BY_ID_REQUEST_SUCCESS';

export const CREATE_COMMENT_REQUEST = '@product/CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_REQUEST_FAIL = '@product/CREATE_COMMENT_REQUEST_FAIL';
export const CREATE_COMMENT_REQUEST_SUCCESS = '@product/CREATE_COMMENT_REQUEST_SUCCESS';

export const SOCKET_PRODUCT_UPDATED = '@@socket/PRODUCT_UPDATED';
export const STOCK_PRODUCT_UPDATED = '@@socket/STOCK_PRODUCT_UPDATED';

export const SOCKET_UNIT_UPDATED = '@@socket/UNIT_UPDATED';
export const SOCKET_UNIT_DELETED = '@@socket/UNIT_DELETED';
