
export const PAGE_IN_PROCESS = '@page/PAGE_IN_PROCESS';

export const GET_TYPES_REQUEST = '@main/GET_TYPES_REQUEST';
export const GET_TYPES_REQUEST_FAIL = '@main/GET_TYPES_REQUEST_FAIL';
export const GET_TYPES_REQUEST_SUCCESS = '@main/GET_TYPES_REQUEST_SUCCESS';

export const GET_CATEGORIES_REQUEST = '@main/GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_REQUEST_FAIL = '@main/GET_CATEGORIES_REQUEST_FAIL';
export const GET_CATEGORIES_REQUEST_SUCCESS = '@main/GET_CATEGORIES_REQUEST_SUCCESS';
